# Site settings
title: 言十年的博客
email: yan@yanshinian.com
description: > # yanshinian 言十年 iOS PHP 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yanshinian.com" # the base hostname & protocol for your site
twitter_username: yanshinian
github_username:  yanshinian

# Build settings
#markdown: kramdown
timezone: Asia/Shanghai
future: true
highlighter: pygments
lsi: true
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]